sudo: required
services:
    - docker

before_install:
    - docker build -t nataphat/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nataphat/docker-react npm run test -- --coverage

