sudo: required
services:
    - docker

before_install:
    - docker build -t nataphat/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nataphat/docker-react npm run test -- --coverage

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "ap-southeast-1"
    app: "docker"
    env: "Docker-env"
    bucker_name: "elasticbeanstalk-ap-southeast-1-666178887374"
    bucker_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_acces_key: $AWS_SECRET_KEY

    

